### ISSUE TITLE
Flight build fails with DEBUG=YES

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1150]
People have written quite a bit of code that fails in debug mode. Mostly missing semi-colons to terminate PIOS_Assert() statements, esp. in F1 SPI. Relates to #1107 (which doesn't fix these). I have meant to raise this for some time as it's very frustrating when running things down.

**Comment by mlyle** [comment]
Fixed by #2073 (and possibly other stuff).... except that targets that are low on space (various F3 targets_ overflow.

**Comment by tracernz** [comment]
Previously fixed by https://github.com/d-ronin/dRonin/pull/1977

**Comment by mlyle** [comment]
Huh, that's true.  (But #1977 doesn't fix the main thing cited in this issue ;)

Anyways --- we're not going to fix this, right?  Nothing realistic to do about debug not fitting...

**Comment by tracernz** [comment]
Yup
